services:
  minio:
    image: minio/minio:RELEASE.2025-02-18T16-25-55Z
    restart: always
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    
  minio-setup:
    depends_on:
      minio:
        condition: service_healthy
    image: minio/mc:RELEASE.2025-02-15T10-36-16Z
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./data:/data
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 minioadmin minioadmin) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb -p minio/datalake;
      /usr/bin/mc policy set public minio/datalake;
      exit 0;
      "

  postgres-iceberg:
    image: postgres:13
    environment:
      POSTGRES_USER: iceberg
      POSTGRES_PASSWORD: iceberg
      POSTGRES_DB: iceberg_catalog
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iceberg -d iceberg_catalog"]
      interval: 10s
      timeout: 5s
      retries: 5

  rest:
    image: tabulario/iceberg-rest:1.6.0
    ports:
      - "8181:8181"
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://datalake/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
      - CATALOG_S3_PATH__STYLE__ACCESS=true
      - CATALOG_URI=jdbc:postgresql://postgres-iceberg:5432/iceberg_catalog?user=iceberg&password=iceberg
      - CATALOG_JDBC_DRIVER=org.postgresql.Driver
      - CATALOG_JDBC_USER=iceberg
      - CATALOG_JDBC_PASSWORD=iceberg
    depends_on:
      postgres-iceberg:
        condition: service_healthy
      minio:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  trino:
    image: trinodb/trino:476
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    depends_on:
      - rest

  spark-iceberg:
    image: tabulario/spark-iceberg:3.5.5_1.8.1
    depends_on:
      - rest
      - minio
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
    ports:
      - "8888:8888"
      - "8088:8080"
      - "10000:10000"
      - "10001:10001"

  postgres-oltp:
    image: postgres:13
    container_name: postgres-oltp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: oltp
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d oltp"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-oltp-data:/var/lib/postgresql/data
  
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    hostname: clickhouse
    environment:
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
      CLICKHOUSE_DB: default
    volumes:
      - ./clickhouse-data:/var/lib/clickhouse
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:9002:9002'
    depends_on:
      - minio
      - minio-setup
    healthcheck:
      test: ["CMD", "curl", "-f", "-u", "clickhouse:clickhouse", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  greenplum:
    image: datagrip/greenplum:6.8
    container_name: greenplum
    environment:
      GP_USER: gpadmin
      GP_PASSWORD: gpadmin
      GP_DB: gpdb
    # entrypoint: | #Не трогать: переопределяет entrypoint внутри контейнера, чтобы можно было использовать env из docker-compose
    #   /bin/bash -c "
    #   until PGPASSWORD=pivotal psql -h greenplum -p 5432 -U tester -d testdb -c 'CREATE USER gpadmin WITH PASSWORD '\\''gpadmin'\\'' SUPERUSER;'; do sleep 1; done;
    #   PGPASSWORD=pivotal psql -h greenplum -p 5432 -U tester -d testdb -c 'CREATE DATABASE gpdb WITH OWNER gpadmin;';
    #   exit 0;
    #   "
    ports:
      - "5435:5432"
    volumes:
      - ./greenplum-data:/var/lib/gpdb/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gpadmin -d gpdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:4.3.0
    container_name: kafka
    environment:
      # KRaft-режим
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # Dev-настройки
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # Отключаем JMX (на всякий случай)
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote=false"
    ports:
      - "9092:9092"
    volumes:
      - ./kafka-data:/tmp/kafka-logs   # стандартный путь для хранения данных
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-init:
    image: apache/kafka:4.3.0   # тот же образ, что и у брокера
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: >
      /bin/bash -c "
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic test_topic --partitions 1 --replication-factor 1;
      echo '>>> Kafka test topic created (or already exists)';
      exit 0;
      "